=== RomoloPoliti-INAF/PhDCourse2021/xml/schemaNew2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="utenti">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="utente"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="utente">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nome"/>
        <xs:element ref="cognome"/>
        <xs:element ref="indirizzo"/>
      </xs:sequence>
      <xs:attribute name="anni" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="nome" type="xs:string"/>
  <xs:element name="cognome" type="xs:string"/>
  <xs:element name="indirizzo" type="xs:string"/>
</xs:schema>

=== RomoloPoliti-INAF/PhDCourse2021/xml/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
    <utenti 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="schemaNew2.xsd">
        <utente anni="20">
            <nome>nome0</nome>
            <cognome>cognome0</cognome>
            <indirizzo>indirizzo0</indirizzo>
        </utente>
        <utente  anni="30">
            <nome>nome2</nome>
            <cognome>cognome2</cognome>
            <indirizzo>indirizzo2</indirizzo>
        </utente>
    </utenti>
